#include "mainwindow.h"
#include "ui_mainwindow.h" // This header is generated by uic from mainwindow.ui
#include <QEvent>
#include <QMouseEvent>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow) // Create an instance of the UI class
    , chipWindow(nullptr) // 初始化为nullptr
{
    ui->setupUi(this); // Set up the UI defined in mainwindow.ui for this window
    
    // 安装事件过滤器到CPU标签
    ui->label_4->installEventFilter(this);
    // 设置鼠标样式，表明可以点击
    ui->label_4->setCursor(Qt::PointingHandCursor);
}

MainWindow::~MainWindow()
{
    delete ui; // Clean up the UI instance
    if (chipWindow) {
        delete chipWindow;
    }
}

// 事件过滤器，处理CPU标签的点击
bool MainWindow::eventFilter(QObject *watched, QEvent *event)
{
    if (watched == ui->label_4 && event->type() == QEvent::MouseButtonRelease) {
        QMouseEvent *mouseEvent = static_cast<QMouseEvent*>(event);
        if (mouseEvent->button() == Qt::LeftButton) {
            // 创建并显示ChipWindow
            if (!chipWindow) {
                chipWindow = new ChipWindow(this);
            }
            chipWindow->show();
            // 可选：隐藏当前窗口
            // this->hide();
            return true; // 事件已处理
        }
    }
    // 其他事件传递给父类处理
    return QMainWindow::eventFilter(watched, event);
} 