#include "mainwindow.h"
#include "ui_mainwindow.h" // This header is generated by uic from mainwindow.ui

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow) // Create an instance of the UI class
{
    ui->setupUi(this); // Set up the UI defined in mainwindow.ui for this window

    // Example: If you added a QLabel named 'statusLabel' in Designer, you could set its text:
    // if (ui->statusLabel) { // Always good to check if the UI element exists
    //     ui->statusLabel->setText("UI Loaded Successfully!");
    // }
}

MainWindow::~MainWindow()
{
    delete ui; // Clean up the UI instance
} 